In [1]:
# numpy is a package for math processing in python
import numpy as np

In [3]:
# 1. how to claim vector and matrix

# array to represent vector
a = np.array([1,2,3])
type(a)

# array vs list 
# array all the elements must be in the same type
# list they can vary any types

numpy.ndarray

In [16]:
b = np.matrix([1,2,3])
c = np.array([[1,2,3]])

In [17]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(1, 3)
(1, 3)


In [11]:
# 2. simple matrix and vector operation

dtype('int32')

In [19]:
# elemensie operation
# + is the elementwise sum up
# a = [x,y,z]
# b = [k,w,c]
# a + b = [x+k, y+w, z+c]
a + a

array([2, 4, 6])

In [21]:
# * is the elementwise sum up
# a = [x,y,z]
# b = [k,w,c]
# a * b = [x*k, y*w, z*c]
a*a

array([1, 4, 9])

In [22]:
np.dot(a,a)

14

In [24]:
sum(a*a.T)

14

In [28]:
# 3. how to create the matrix and vector in some tricks
np.arange(3,10,2)

array([3, 5, 7, 9])

In [29]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [31]:
np.zeros(10) + 4

array([ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.])

In [33]:
np.linspace(0, 100, 11)

array([   0.,   10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,
         90.,  100.])

In [36]:
np.random.uniform(size=4)

array([ 0.4516913 ,  0.41257144,  0.59695695,  0.47254315])

In [49]:
# 4. how to compare 2 array
a = [1,2,3.0000000001]
b = [1,2,3]
a == b

False

In [50]:
a = np.array(a)
b = np.array(b)

In [51]:
# elementwise comparasion
a == b

array([ True,  True, False], dtype=bool)

In [52]:
# overal comparasion
np.array_equal(a, b)

False

In [53]:
# similarity
# a = [x, y, z]
# b = [x+-k, y+-k, z+-k]
# 1e-05 is very small number 0.00001
np.allclose(a, b, rtol=1e-05)

True

In [54]:
# more linear operaion for matrix
A = np.matrix([[1,2,3],[2,3,4],[3,1,2]])

In [55]:
A

matrix([[1, 2, 3],
        [2, 3, 4],
        [3, 1, 2]])

In [56]:
print(A + A)

[[2 4 6]
 [4 6 8]
 [6 2 4]]


In [57]:
print(A*2)

[[2 4 6]
 [4 6 8]
 [6 2 4]]


In [58]:
print(A + 2)

[[3 4 5]
 [4 5 6]
 [5 3 4]]


In [59]:
print(A*3+ A*2 + 10)

[[15 20 25]
 [20 25 30]
 [25 15 20]]


In [61]:
A = np.matrix([[1,2],[3,4],[3,1]])
B = np.matrix([[1,2,3],[2,3,4]])

In [62]:
print(A)
print(B)

[[1 2]
 [3 4]
 [3 1]]
[[1 2 3]
 [2 3 4]]


In [63]:
# matrix multiplication
np.dot(A, B) #(3,2)* (2,3) => (3,3)

matrix([[ 5,  8, 11],
        [11, 18, 25],
        [ 5,  9, 13]])

In [64]:
np.dot(B,A) #(2,3)* (3,2) => (2,2)

matrix([[16, 13],
        [23, 20]])

In [65]:
a = np.array(A)
b = np.array(B)

In [66]:
a,b

(array([[1, 2],
        [3, 4],
        [3, 1]]), array([[1, 2, 3],
        [2, 3, 4]]))

In [71]:
a = a.reshape(-1)
b = b.reshape(-1)

In [74]:
c = a*b

In [75]:
c.reshape(2,3)

array([[1, 4, 9],
       [8, 9, 4]])

In [79]:
# vertical append
np.vstack((a,a))

array([[1, 2, 3, 4, 3, 1],
       [1, 2, 3, 4, 3, 1]])

In [80]:
# honrizental append
np.hstack((a,a))

array([1, 2, 3, 4, 3, 1, 1, 2, 3, 4, 3, 1])

In [81]:
# FYI :https://www.youtube.com/watch?v=aKhhYguY0DQ&list=PLFD0EB975BA0CC1E0&index=2

In [86]:
# Q1: 
a = np.arange(2,7,2)
a

array([2, 4, 6])

In [88]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [90]:
sum(a * b.T)

28

In [91]:
np.dot(a, b)

28

In [92]:
# training and inference ==> regression!!!

In [96]:
import pandas as pd

br = pd.read_excel("BatonRouge.xls")

br.head()

OSError: [Errno 22] Invalid argument: 'Desktop:\\BatonRouge.xls'

In [97]:
# dummy variable
import numpy as np
np.unique(br[['Style']].values)


NameError: name 'br' is not defined

In [98]:
s = pd.Series(list('abcabababababcccababab'))

In [100]:
pd.get_dummies(s)
# a = 1 - b -c => multicolinearity
s = pd.get_dummies(s, drop_first=True)
s

b  c
0   0  0
1   1  0
2   0  1
3   0  0
4   1  0
5   0  0
6   1  0
7   0  0
8   1  0
9   0  0
10  1  0
11  0  0
12  1  0
13  0  1
14  0  1
15  0  1
16  0  0
17  1  0
18  0  0
19  1  0
20  0  0
21  1  0

In [101]:
# 1 dummy variables with k types
# 2 create k-1 binary columns to represent this column
# pd.get_dummies(s, drop_first=True)

In [102]:
br.head()

NameError: name 'br' is not defined

In [103]:
all_correlations = br.corr()

# affinity table
all_correlations

NameError: name 'br' is not defined

In [104]:
%matplotlib inline
import matplotlib.pyplot as plt

y = br['Price']
x = br['SQFT']

fig = plt.figure()
plt.xlabel("SQFT")
plt.ylabel("Price")
plt.scatter(x, y, alpha=0.25)
plt.show()

NameError: name 'br' is not defined

In [105]:
import statsmodels.api as sm

# beta 0! to add 1 for the first column!
x_with_intercept = sm.add_constant(x, prepend=True)

x_with_intercept.head()

C:\Program Files\Anaconda3-5.0.1x64\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


NameError: name 'x' is not defined

In [106]:
# creat the model
model = sm.OLS(y, x_with_intercept)

# learning the model with a, b
results = model.fit()

print(results.summary())

# R square, the higher the better
# F the higher the better
# p-vale: > 0.05, the x and y has liear correlation, none otherwise

NameError: name 'y' is not defined

In [107]:
import statsmodels.formula.api as smf

formula = "Price ~ SQFT"

model_formula = smf.ols(formula = formula, data = br)

results_formula = model_formula.fit()

# This should be exactly the same as the non-formula method
print(results_formula.summary())

NameError: name 'br' is not defined

In [108]:
import numpy as np

# create a range of values to represent X
min_x = np.min(x)
max_x = np.max(x)
x_points = np.linspace(min_x, max_x, 100)

# is to calculate y values using X with our model
y_model = results.params[0] + results.params[1] * x_points

NameError: name 'x' is not defined

In [109]:
x_model = np.array([np.ones(100), x_points])
x_model = x_model.transpose()

y_model = results.predict(x_model)
fig = plt.figure()

plt.scatter(x, y, alpha = 0.1)

plt.plot(x_points, y_model, color = "red")

plt.xlabel("SQFT")
plt.ylabel("Price")

plt.show()

NameError: name 'x_points' is not defined

In [110]:
# to test your model
new_house = [1, 1500]

results.predict(new_house)

NameError: name 'results' is not defined

In [111]:
new_house_dict = {'SQFT': [1500, 3400]}

results_formula.predict(new_house_dict)

NameError: name 'results_formula' is not defined

In [112]:
# all columns to predict our model?
x = br.iloc[:, 1:] # get rid of first column, in here is price 

x_with_dummies = pd.get_dummies(x, drop_first=True) # processing the dummy values

x_with_dummies_intercept = sm.add_constant(x_with_dummies, prepend=True) # appending '1' into the first columns to get beta0

NameError: name 'br' is not defined

In [113]:
x_with_dummies_intercept

NameError: name 'x_with_dummies_intercept' is not defined

In [114]:
model_multivariate = sm.OLS(y, x_with_dummies_intercept)

results_multivariate = model_multivariate.fit()

# now you see R-square is higher : )
print(results_multivariate.summary())

NameError: name 'y' is not defined